Style/SymbolArray:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Security/YAMLLoad:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Layout/LineLength:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/WordArray:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
